#!/usr/bin/env bash
set -e

function usage() {
    echo 1>&2 "Usage: $0 -t TAG ENVIRONMENT [ ENVIRONMENTS ... ]"
    echo 1>&2 "    (use to force linked environments to same build host"
    echo 1>&2 "     for use under Jenkins, to maximize caching and minimize"
    echo 1>&2 "     build times)"
    exit 2
}

OPTIND=1
while getopts ':t:' opt; do
    case $opt in
	h)
	    usage
	    ;;
	t)
	    TAG=${OPTARG}
	    ;;
	\?)
	    usage
	    ;;
    esac
done
shift $((OPTIND - 1))
envs=$*

if [ -z "${envs}" ]; then
    usage
fi

for e in ${envs}; do
    ./bld -e ${e} ${TAG}
done
