#!/bin/bash
set -e

function usage() {
    echo 1>&2 "Usage: $0 [-d] [-x] [-j] [-b BASE_IMAGE] \\"
    echo 1>&2 "           [-n IMAGE_NAME ] TAG"
    echo 1>&2 "  -d enables dry run (no Docker build or push)"
    echo 1>&2 "  -x is 'do not push' (but does build)."
    echo 1>&2 "  -j adds 'exp_' to front and '_jlbleed' to end of tag."
    echo 1>&2 "  default BASE_IMAGE='lsstsqre/sciplat-lab'"
    echo 1>&2 "  default IMAGE_NAME='lsstsqre/sal-sciplat-lab'"
    echo 1>&2 "  typical TAG='w_2017_35'"
    exit 2
}

OPTIND=1
DRY_RUN=0
NOPUSH=0
JLBLEED=0
BASE_IMAGE="lsstsqre/sciplat-lab"
IMAGE_NAME="lsstsqre/sal-sciplat-lab"
TAG_PREFIX=""
while getopts ':hdxjn:b:' opt; do
    case $opt in
    h)
        usage
        ;;
    d)
        DRY_RUN=1
        ;;
    x)
        NOPUSH=1
        ;;
    j)
	JLBLEED=1
	;;
    b)
        BASE_IMAGE=${OPTARG}
        ;;
    n)
        IMAGE_NAME=${OPTARG}
        ;;
    \?)
        usage
        ;;
    esac
done
shift $((OPTIND - 1))
TAG=${1}
if [ -z "${TAG}" ] || [ $# -gt 1 ]; then
    usage
fi
VERSION=${TAG/#v/r}
if [ "${JLBLEED}" -eq 1 ] ; then
    VERSION="exp_${VERSION}_jlbleed"
fi
sed -e "s|{{BASE_IMAGE}}|${BASE_IMAGE}|g" \
    -e "s|{{IMAGE_NAME}}|${IMAGE_NAME}|g" \
    -e "s|{{VERSION}}|${VERSION}|g" \
    -e "s|{{TAG}}|${TAG}|g" \
    < Dockerfile.template > Dockerfile
if [ "${NOPUSH}" -eq 1 ]; then
    VERSION="nopush_${VERSION}"
fi
if [ "${DRY_RUN}" -ne 0 ]; then
    echo 1>&2 "Dry run: Dockerfile written, stopping before build/push."
    exit 0
fi
./bld_1
